/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EventsRouteImport } from './routes/events'
import { Route as JoinRouteImport } from './routes/join'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResourcesIndexRouteImport } from './routes/resources.index'
import { Route as ResourcesSlugRouteImport } from './routes/resources.$slug'
import { Route as ApiAdminUploadRouteImport } from './routes/api/admin/upload'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResourcesRoute,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ResourcesRoute,
} as any)
const ApiAdminUploadRoute = ApiAdminUploadRouteImport.update({
  id: '/api/admin/upload',
  path: '/api/admin/upload',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/join': typeof JoinRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/resources/': typeof ResourcesIndexRoute
  '/api/admin/upload': typeof ApiAdminUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/join': typeof JoinRoute
  '/privacy': typeof PrivacyRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/resources': typeof ResourcesIndexRoute
  '/api/admin/upload': typeof ApiAdminUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/join': typeof JoinRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/resources/': typeof ResourcesIndexRoute
  '/api/admin/upload': typeof ApiAdminUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/community'
    | '/contact'
    | '/events'
    | '/join'
    | '/privacy'
    | '/resources'
    | '/reviews'
    | '/services'
    | '/terms'
    | '/resources/$slug'
    | '/resources/'
    | '/api/admin/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/community'
    | '/contact'
    | '/events'
    | '/join'
    | '/privacy'
    | '/reviews'
    | '/services'
    | '/terms'
    | '/resources/$slug'
    | '/resources'
    | '/api/admin/upload'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/community'
    | '/contact'
    | '/events'
    | '/join'
    | '/privacy'
    | '/resources'
    | '/reviews'
    | '/services'
    | '/terms'
    | '/resources/$slug'
    | '/resources/'
    | '/api/admin/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  JoinRoute: typeof JoinRoute
  PrivacyRoute: typeof PrivacyRoute
  ResourcesRoute: typeof ResourcesRouteWithChildren
  ReviewsRoute: typeof ReviewsRoute
  ServicesRoute: typeof ServicesRoute
  TermsRoute: typeof TermsRoute
  ApiAdminUploadRoute: typeof ApiAdminUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/api/admin/upload': {
      id: '/api/admin/upload'
      path: '/api/admin/upload'
      fullPath: '/api/admin/upload'
      preLoaderRoute: typeof ApiAdminUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ResourcesRouteChildren {
  ResourcesSlugRoute: typeof ResourcesSlugRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesSlugRoute: ResourcesSlugRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  JoinRoute: JoinRoute,
  PrivacyRoute: PrivacyRoute,
  ResourcesRoute: ResourcesRouteWithChildren,
  ReviewsRoute: ReviewsRoute,
  ServicesRoute: ServicesRoute,
  TermsRoute: TermsRoute,
  ApiAdminUploadRoute: ApiAdminUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
